        <div class="col-xs-11">
            <form name="theForm" id="theForm" class="form-horizontal" action="<?php echo $this->escapeHtml($this->action);?>" method="post">
                <div class="form-group">
                    <label for="resource" class="col-sm-3 control-label no-padding-right">Resource</label>
                    <div class="col-sm-9">
                        <input id="resource" name="resource" class="col-xs-9 col-sm-9">
                    </div>
                </div>
            </form>
        </div>
