        <form name="theForm" id="theForm" action="<?php echo $this->escapeHtml($this->action);?>" method="post">
            <table class="table table-bordered table-responsive">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Response</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><?php echo $this->escapeHtml($this->id);?></td>
                        <td><?php echo $this->escapeHtml($this->description);?></td>
                    </tr>
                </tbody>
            </table>
            <input type="hidden" name="id" id="id" value="<?php echo $this->escapeHtml($this->id);?>"/>
        </form>