            <form id="theForm" class="form-horizontal" role="form" method="post" action="<?php echo $this->url('track',array('action'=>'add'));?>">
                <div class="form-group">
                    <label for="inputTitle" class="col-sm-2 control-label"><?php echo $this->translate('Title');?></label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputTitle" name="inputTitle" placeholder="Title">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputDescription" class="col-sm-2 control-label"><?php echo $this->translate('Description');?></label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="inputDescription" name="inputDescription" placeholder="Description"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputYear" class="col-sm-2 control-label"><?php echo $this->translate('Year');?></label>
                    <div class="col-sm-1">
                        <input type="text" class="form-control" id="inputYear" name="inputYear" placeholder="Year">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputCategory" class="col-sm-2 control-label"><?php echo $this->translate('Category');?></label>
                    <div class="col-sm-2">
                        <select class="form-control" id="inputCategory" name="inputCategory">
                            <?php if(isset($categories)):?>
                                <?php foreach($categories as $category): ?>
                                    <option value="<?php echo $category->getId();?>"><?php echo $category->getName();?></option>

                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button id="id-btn-save" type="submit" class="btn btn-default">Save</button>
                        <button type="reset" class="btn btn-default">Reset</button>
                        <button id="id-btn-cancel" type="button" class="btn btn-default">Cancel</button>
                    </div>
                </div>
            </form>

