<form id="theForm" class="form-horizontal" role="form" method="post" action="<?php echo $this->url('track', array('action'=>'delete','id'=>$trackinfo['id'])) ;?>">
    <div class="form-group">
        <label for="inputTitle" class="col-sm-2 control-label">Title</label>
        <div class="col-sm-10">
            <p class="form-control-static"><?php echo $this->escapeHtml($trackinfo['title']);?></p>
        </div>
    </div>
    <div class="form-group">
        <label for="inputDescription" class="col-sm-2 control-label">Description</label>
        <div class="col-sm-10">
            <p class="form-control-static"><?php echo $this->escapeHtml($trackinfo['description']);?></p>
        </div>
    </div>
    <div class="form-group">
        <label for="inputYear" class="col-sm-2 control-label">Year</label>
        <div class="col-sm-1">
            <p class="form-control-static"><?php echo $this->escapeHtml($trackinfo['year']);?></p>
        </div>
    </div>
    <div class="form-group">
        <label for="inputCategory" class="col-sm-2 control-label">Category</label>
        <div class="col-sm-2">
            <p class="form-control-static"><?php echo $this->escapeHtml($trackinfo['category_name']);?></p>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Confirm Delete</button>
            <button type="reset" class="btn btn-default">Reset</button>
            <button id="id-btn-cancel" type="button" class="btn btn-default">Cancel</button>
        </div>
    </div>
    <input type="hidden" id="inputId" name="inputId" value="<?php echo $trackinfo['id'];?>">
</form>

