            <form id="theForm" class="form-horizontal" role="form" method="post" action="<?php echo $this->url('track', array('action'=>'edit','id'=>$trackinfo['id'])) ;?>">
                <div class="form-group">
                    <label for="inputTitle" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputTitle" name="inputTitle" placeholder="Title" value="<?php echo $this->escapeHtml($trackinfo['title']);?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputDescription" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="inputDescription" name="inputDescription" placeholder="Description"><?php echo $this->escapeHtml($trackinfo['description']);?></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputYear" class="col-sm-2 control-label">Year</label>
                    <div class="col-sm-1">
                        <input type="text" class="form-control" id="inputYear" name="inputYear" placeholder="Year" value="<?php echo $this->escapeHtml($trackinfo['year']);?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputCategory" class="col-sm-2 control-label">Category</label>
                    <div class="col-sm-2">
                        <select class="form-control" id="inputCategory" name="inputCategory">
                            <?php if(isset($categories)):?>
                                <?php foreach($categories as $category): ?>
                                    <option value="<?php echo $category->getId();?>" <?php if($trackinfo['category_id'] === $category->getId()) { echo 'selected'; } ?>><?php echo $category->getName();?></option>

                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Update</button>
                        <button type="reset" class="btn btn-default">Reset</button>
                        <button id="id-btn-cancel" type="button" class="btn btn-default">Cancel</button>
                    </div>
                </div>
                <input type="hidden" id="inputId" name="inputId" value="<?php echo $trackinfo['id'];?>">
            </form>

